Notebook is used to load .h5 data that comes out of the sequencer and merges them to one AnnData input file by the end

In [1]:
import numpy as np
import pandas as pd
import scanpy as sc
import os
import anndata as ad
from pathlib import Path

sc.settings.verbosity = 3             # verbosity: errors (0), warnings (1), info (2), hints (3)
sc.logging.print_header()
sc.settings.set_figure_params(dpi=80, facecolor='white')

wd = Path('/Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5')
conditions_list_os = sorted([f[:-3] for f in os.listdir(wd) if f.endswith(".h5")])
conditions_dict = dict.fromkeys(conditions_list_os)

In [2]:

metadata = pd.read_csv("/Users/annisa/Box Sync/G7/scales_run_ipynb/ConditionsMatrixCombined.csv", index_col=0)
metadata = metadata[metadata["ancestry"] == 0] # select evolved only

In [3]:
metadata

,rich_media,synthetic_media,30c,37c,dglucose,glyetoh,ros,h2o2,diamide,osmolytes,sorbitol,kcl,shuffle,ancestry,stress
condition,,,,,,,,,,,,,,,
anc_sceg-30,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0
anc_sceg-37,0,1,0,1,0,1,0,0,0,0,0,0,1,0,0
anc_sdc,0,1,1,0,1,0,0,0,0,0,0,0,0,0,1
anc_sdc-37,0,1,0,1,1,0,0,0,0,0,0,0,1,0,0
anc_sdc-diam,0,1,1,0,1,0,1,0,1,0,0,0,1,0,0
anc_sdc-h2o2,0,1,1,0,1,0,1,1,0,0,0,0,0,0,0
anc_sdc-kcl,0,1,1,0,1,0,0,0,0,1,0,1,1,0,0
anc_sdc-kcl-diam,0,1,1,0,1,0,1,0,1,1,0,1,1,0,0
anc_sdc-kcl-h2o2,0,1,1,0,1,0,1,1,0,1,0,1,0,0,0
anc_sdc-sorb,0,1,1,0,1,0,0,0,0,1,1,0,1,0,0
anc_ypd,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1
anc_ypd-37,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0
anc_ypd-diam,1,0,1,0,1,0,1,0,1,0,0,0,1,0,0
anc_ypd-h2o2,1,0,1,0,1,0,1,1,0,0,0,0,1,0,0
anc_ypd-kcl,1,0,1,0,1,0,0,0,0,1,0,1,0,0,0
anc_ypd-kcl-diam,1,0,1,0,1,0,1,0,1,1,0,1,1,0,0
anc_ypd-kcl-h2o2,1,0,1,0,1,0,1,1,0,1,0,1,0,0,0
anc_ypd-sorb,1,0,1,0,1,0,0,0,0,1,1,0,0,0,0
anc_ypeg-30,1,0,1,0,0,1,0,0,0,0,0,0,1,0,0
anc_ypeg-37,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0

In [4]:
for index, row in metadata.iterrows():
    adata = sc.read_10x_h5(wd / f"{index}.h5")
    adata.obs_names = [f"{index}_{bc}" for bc in adata.obs_names]
    adata.var_names_make_unique()
    for k, v in row.items():
        adata.obs[k] = v
    conditions_dict[index] = adata

reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_sceg-30.h5
 (0:00:00)
reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_sceg-37.h5
 (0:00:00)
reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_sdc.h5
 (0:00:00)
reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_sdc-37.h5
 (0:00:00)
reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_sdc-diam.h5
 (0:00:00)
reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_sdc-h2o2.h5
 (0:00:00)
reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_sdc-kcl.h5
 (0:00:00)
reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_sdc-kcl-diam.h5
 (0:00:00)
reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_sdc-kcl-h2o2.h5
 (0:00:00)
reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_sdc-sorb.h5
 (0:00:00)
reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_ypd.h5
 (0:00:00)
reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_ypd-37.h5
 (0:00:00)
reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_ypd-diam.h5
 (0:00:00)
reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_ypd-h2o2.h5
 (0:00:00)
reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_ypd-kcl.h5
 (0:00:00)
reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_ypd-kcl-diam.h5
 (0:00:00)
reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_ypd-kcl-h2o2.h5
 (0:00:00)
reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_ypd-sorb.h5
 (0:00:00)
reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_ypeg-30.h5
 (0:00:00)
reading /Users/annisa/Box Sync/G7/all_nova_filtered/anc_h5/anc_ypeg-37.h5
 (0:00:00)

In [5]:
newadatas = ad.concat(conditions_dict, label="condition")
newadatas.obs_names.duplicated().sum() #check for 0

np.int64(0)

In [6]:
#newadatas.var_names_make_unique()
newadatas.write("mergedh5_nova_anc_CRfiltered.h5ad")

In [7]:
newadatas.obs

,rich_media,synthetic_media,30c,37c,dglucose,glyetoh,ros,h2o2,diamide,osmolytes,sorbitol,kcl,shuffle,ancestry,stress,condition
anc_sceg-30_AAACCCAAGGTAGTAT-1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,anc_sceg-30
anc_sceg-30_AAACCCACAGAATGTA-1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,anc_sceg-30
anc_sceg-30_AAACGAAAGGTCGTGA-1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,anc_sceg-30
anc_sceg-30_AAACGAAGTAGTGGCA-1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,anc_sceg-30
anc_sceg-30_AAACGCTGTAGACGGT-1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,anc_sceg-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
anc_ypeg-37_TTTGGTTTCATCGACA-1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,anc_ypeg-37
anc_ypeg-37_TTTGTTGAGAGCATTA-1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,anc_ypeg-37
anc_ypeg-37_TTTGTTGCACTAAACC-1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,anc_ypeg-37
anc_ypeg-37_TTTGTTGCAGGAGGTT-1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,anc_ypeg-37
anc_ypeg-37_TTTGTTGTCAACCCGG-1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,anc_ypeg-37

In [9]:
newadatas.obs.value_counts('condition')

condition
anc_ypd-kcl-diam    6343
anc_ypd-kcl-h2o2    5440
anc_ypd-sorb        4236
anc_sdc-kcl-h2o2    3844
anc_ypeg-30         3659
anc_sceg-30         3353
anc_sdc-kcl-diam    3191
anc_sdc-sorb        3123
anc_ypd-h2o2        2862
anc_ypd-kcl         2846
anc_ypd             2844
anc_sdc-h2o2        2813
anc_sdc-37          2767
anc_sdc-kcl         2756
anc_sdc             2313
anc_ypeg-37         2260
anc_sceg-37         2212
anc_sdc-diam        2056
anc_ypd-37          1534
anc_ypd-diam         404
Name: count, dtype: int64